server:
  service:
    type: LoadBalancer
  global:
    scrape_interval: 1m
    scrape_timeout: 10s
    evaluation_interval: 1m

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

serverFiles:
  prometheus.yml:
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
    scrape_configs:
    - job_name: 'skywalking-self-o11y'
      metrics_path: '/metrics'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - sw-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_name, __meta_kubernetes_pod_container_port_name]
        action: keep
        regex: oap;http-monitoring
      - source_labels: []
        target_label: service
        replacement: oap-server
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: host_name
        regex: (.+)
        replacement: $$1
      scrape_interval: 30s
      scrape_timeout: 10s
